---
exp_name: 'concated_cnn_to_gru'

# Input parameters.
spa_width: 100
spa_length: 140
ang_width: 125
ang_length: 125

feature_size: 16
hidden_size: 64
seqeunce_length: 100

# Hyperparameters
max_epoch: 100
batch_size: 4
num_workers: 8
weight_decay: 0.5                     # Weight decay.
lr: 0.05                          # Initial learning rate.

# lr_scheduler.MultiStepLR
step_size: [30, 50, 70]                 # How often to decay learning rate.
gamma: 0.1                          # How much to decay learning rate.

# lr_scheduler.CosineAnnealingLR
eta_min: 0.0001                     # Minimum learning rate.
Tmax: 30                            # Periodic epochs of reducing learning rate.
