---
exp_name: 'sim_1st'

img_model: 'model.network.Net_v2'

# Input parameters.
spa_width: 153
spa_length: 153
ang_width: 128
ang_length: 128

feature_size: 32
hidden_size: 64
sequence_length: 100

# Hyperparameters
EPOCHS: 50
max_epoch: 100
batch_size: 8
num_workers: 0
weight_decay: 0.5                     # Weight decay.
lr: 0.0001                          # Initial learning rate.

# lr_scheduler.MultiStepLR
step_size: [30, 50, 70]                 # How often to decay learning rate.
gamma: 0.1                          # How much to decay learning rate.

# lr_scheduler.CosineAnnealingLR
eta_min: 0.0001                     # Minimum learning rate.
Tmax: 30                            # Periodic epochs of reducing learning rate.
